[general]
# Temperaturas: 5700K (día - natural) y 3500K (noche - naranja cálido)
temp-day=5700
temp-night=3500

# Transición suave entre estados
fade=1

# Proveedor de ubicación manual para evitar errores de geoclue en Fedora Atomic
location-provider=manual

[manual]
# Coordenadas exactas para Dublín, IE
lat=53.3
lon=-6.2

